services:
  # Laravel Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: presenter-backend
    ports:
      - "8000:8000"
    volumes:
      - backend_vendor:/var/www/html/vendor
      - backend_storage:/var/www/html/storage
      - backend_bootstrap_cache:/var/www/html/bootstrap/cache
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=presenter_v3
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
    depends_on:
      - postgres
    networks:
      - presenter-network

  # React Frontend  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: presenter-frontend
    ports:
      - "3000:3000"
    volumes:
      - frontend_node_modules:/app/node_modules
    networks:
      - presenter-network

  # PostgreSQL Database
  postgres:
    image: postgres:17
    container_name: presenter-postgres
    environment:
      - POSTGRES_DB=presenter_v3
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - presenter-network

  # PostgreSQL Admin Interface
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: presenter-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - presenter-network

volumes:
  backend_vendor:
  backend_storage:
  backend_bootstrap_cache:
  frontend_node_modules:
  postgres_data:

networks:
  presenter-network:
    driver: bridge